# This file is forked from https://github.com/pubref/rules_protobuf/blob/110f8e238ff7b3d7c6298445cd2f9535f0df7bbe/.travis.yml.

# trusty beta image has jdk8, gcc4.8.4
dist: trusty
sudo: required

# Bazel installation requires JDK 8
language: java

os:
  - linux

env:
  - BAZEL_VERSION=0.11.1

before_install:
  - |
    sudo apt-get install clang-format
    BAZEL_VERSION=0.11.1
    OS=linux
    BAZEL_URL="https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-${OS}-x86_64.sh"
    sysctl kernel.unprivileged_userns_clone=1
    wget -O install.sh "${BAZEL_URL}"
    chmod +x install.sh
    ./install.sh --user
    rm -f install.sh
script:
  - |
    bazel \
      --output_base=$HOME/.cache/bazel \
      --batch \
      --host_jvm_args=-Xmx500m \
      --host_jvm_args=-Xms500m \
      test \
      ... \
      --worker_verbose \
      --verbose_failures \
      --test_output=errors \
      --spawn_strategy=sandboxed \
      --genrule_strategy=sandboxed \
      --local_resources=400,2,1.0 \
      --strategy=Javac=worker \
      --strategy=Closure=worker
notifications:
  email: false
