cc_library(
    name = "mahjong_score_calculator_lib",
    srcs = [
      "hand_parser.cc",
      "mahjong_common_utils.cc",
      "mahjong_common_value.cc",
      "score_calculator.cc",
      "yaku_applier.cc",
    ],
    hdrs = [
      "hand_parser.h",
      "mahjong_common_utils.h",
      "mahjong_common_value.h",
      "score_calculator.h",
      "yaku_applier.h",
    ],
    deps = [
      "//proto:mahjong-scorecalculator",
    ],
    visibility = ["//visibility:public"],
)
