cc_library(
    name = "mahjong_score_calculator_lib",
    srcs = [
      "HandParser.cpp",
      "MahjongCommonUtils.cpp",
      "MahjongCommonValue.cpp",
      "ScoreCalculator.cpp",
      "YakuApplier.cpp",
    ],
    hdrs = [
      "HandParser.h",
      "MahjongCommonUtils.h",
      "MahjongCommonValue.h",
      "ScoreCalculator.h",
      "YakuApplier.h",
    ],
    deps = [
      "//proto:mahjong-scorecalculator",
    ],
    visibility = ["//visibility:public"],
)
